/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type ItemTransformer from '#transformers/item_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Item = InferData<ItemTransformer>
  export namespace Item {
    export type Variants = InferVariants<ItemTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
